#NumTokens
org.irlib.features.preRetrieval.NumberOfTokens
#AveTokenLength
org.irlib.features.preRetrieval.AverageTokenLength
#NumUnqTokens
#org.irlib.features.preRetrieval.NumberOfUniqueTokens
#AveIDF
org.irlib.features.preRetrieval.AveIDF
#IDFMaxMinRatio
#MaxIDF
#DevIDF 
org.irlib.features.preRetrieval.IDFRelated
#AveICTF
org.irlib.features.preRetrieval.AveICTF
#SCS
org.irlib.features.preRetrieval.SimplifiedQueryClarity
#maxQCS
#sumQCS
#varQCS
org.irlib.features.preRetrieval.CollQuerySimilarity
#QueryScope
org.irlib.features.preRetrieval.QueryScope